# Generated by Django 4.1.3 on 2022-11-15 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='emais',
            new_name='email',
        ),
    ]
