# Generated by Django 4.1.3 on 2022-11-15 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_receita_pessoa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='Pessoa',
            new_name='pessoa',
        ),
    ]
